name: CI

on:
  push:
    branches: [ "14" ]
  pull_request:
    branches: [ "14" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v4
    - name: Setup Repo
      run: sudo apt-get install repo
    - name: Build
      run: bash build.sh
    - name: ls
      run: |
        ls
        cd build
        ls
